spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/local
#          search-locations: classpath:/@profiles.active@
  profiles:
     active: native

server:
  port: 8888

security:
  user:
    password: 123456
